#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DEFAULT_SERVER_PORT 110
#define DEFAULT_MANAGEMENT_ADDR "127.0.0.1"
#define DEFAULT_MANAGEMENT_PORT 9090
#define DEFAULT_LOCAL_ADDR "0.0.0.0"
#define DEFAULT_LOCAL_PORT 1110
#define DEFAULT_REPLACE_MESSAGE "Parte reemplazada."
#define DEFAULT_MEDIA_TYPES ""
#define DEFAULT_CMD "cat"
#define DEFAULT_ERROR_FILE "/dev/null"
#define POP3_FILTER_VERSION "1.0.0"

#endif